version: '3.8'

services:
  
  gorong-back:
    image: ${DOCKER_USERNAME}/gorong-back:latest
    container_name: gorong-back
    ports:
      - "8080:8080"
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - TOUR_API_KEY=${TOUR_API_KEY}
      - JUSO_API_KEY=${JUSO_API_KEY}
      - JUSO_COORD_API_KEY=${JUSO_COORD_API_KEY}
    restart: always

  
  gorong-front:
    image: ${DOCKER_USERNAME}/gorong-front:latest
    container_name: gorong-front
    ports:
      - "80:80"
    restart: always
