server {
    listen 80;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # React Router를 사용하는 경우 필수 설정!
        try_files $uri $uri/ /index.html;
    }
    # reverse proxy 설정
    # 백엔드 API로 가는 요청을 프록시(대리 전달) 해줄 수도 있습니다.
    location /api/ {
        proxy_pass http://백엔드_서버_주소:8080;
    }
}