spring:
  datasource:
    url: jdbc:postgresql://gorong-db.cwhkwq4kiz9p.us-east-1.rds.amazonaws.com:5432/gorong_db?currentSchema=gorong_schema&option=-c%20search_path%3Dgorong_schema%2Cpublic
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: gorong_schema

tour:
  api:
    service-key: ${TOUR_API_KEY}
    base-url: https://apis.data.go.kr/B551011/KorService1

juso:
  api:
    key: ${JUSO_API_KEY}
  coord:
    key: ${JUSO_COORD_API_KEY}

gemini:
  api:
    key: ${GEMINI_API_KEY}
    model: ${GEMINI_MODEL:gemini-1.5-flash}
    
aws:
  region: us-east-1
  s3:
    bucket: gorong-prod-media-726422254207-us-east-1-an
    base-url: https://gorong-prod-media-726422254207-us-east-1-an.s3.us-east-1.amazonaws.com
  credentials:
    access-key: ${AWS_ACCESS_KEY_ID} # 깃허브 시크릿 및 EC2 환경변수로 주입!
    secret-key: ${AWS_SECRET_ACCESS_KEY}
