version: '3.8'

services:
  # PostGIS가 포함된 PostgreSQL 데이터베이스 컨테이너
  postgres-postgis:
    image: postgis/postgis:15-3.4 # 가장 안정적인 15 버전 사용
    container_name: postgres15
    restart: always
    environment:
      POSTGRES_USER: gorong_user        # DB 접속 아이디
      POSTGRES_PASSWORD: 5432           # DB 접속 비밀번호
      POSTGRES_DB: gorong_db            # 생성될 데이터베이스 이름
      TZ: Asia/Seoul                    # 한국 시간대 설정
    ports:
      - "5432:5432" # 내 컴퓨터의 5432 포트를 컨테이너의 5432 포트와 연결
    volumes:
      # DB 데이터가 날아가지 않도록 내 컴퓨터의 폴더와 동기화 (볼륨 마운트)
      - postgre_data:/var/lib/postgresql/data

volumes:
  gorong_db_data:
